use ea8t2ptee87rhxc4;

insert into Users (user_name, email, password, lastLogin, status, createdAt, updatedAt) values ('Matt Urian', 'email1@email.com', 'password1234', current_timestamp(), 'inactive', current_timestamp(), current_timestamp());
insert into Users (user_name, email, password, lastLogin, status, createdAt, updatedAt) values ('Phillis Dillis', 'email2@email.com', 'password1234', current_timestamp(), 'inactive', current_timestamp(), current_timestamp());
insert into Users (user_name, email, password, lastLogin, status, createdAt, updatedAt) values ('John Phillips', 'email3@email.com', 'password1234', current_timestamp(), 'inactive', current_timestamp(), current_timestamp());
insert into Users (user_name, email, password, lastLogin, status, createdAt, updatedAt) values ('Mark Twain', 'email4@email.com', 'password1234', current_timestamp(), 'inactive', current_timestamp(), current_timestamp());
insert into Users (user_name, email, password, lastLogin, status, createdAt, updatedAt) values ('Tom Petty', 'email5@email.com', 'password1234', current_timestamp(), 'inactive', current_timestamp(), current_timestamp());
insert into Users (user_name, email, password, lastLogin, status, createdAt, updatedAt) values ('Drew Lauck', 'email6@email.com', 'password1234', current_timestamp(), 'inactive', current_timestamp(), current_timestamp());
insert into Users (user_name, email, password, lastLogin, status, createdAt, updatedAt) values ('Matthew Musil', 'email7@email.com', 'password1234', current_timestamp(), 'inactive', current_timestamp(), current_timestamp());
insert into Users (user_name, email, password, lastLogin, status, createdAt, updatedAt) values ('Betty White', 'email8@email.com', 'password1234', current_timestamp(), 'inactive', current_timestamp(), current_timestamp());
insert into Users (user_name, email, password, lastLogin, status, createdAt, updatedAt) values ('Mike Watt', 'email9@email.com', 'password1234', current_timestamp(), 'inactive', current_timestamp(), current_timestamp());
insert into Users (user_name, email, password, lastLogin, status, createdAt, updatedAt) values ('Will Smith', 'email10@email.com', 'password1234', current_timestamp(), 'inactive', current_timestamp(), current_timestamp());
insert into Users (user_name, email, password, lastLogin, status, createdAt, updatedAt) values ('Haley Bailey', 'email11@email.com', 'password1234', current_timestamp(), 'inactive', current_timestamp(), current_timestamp());
insert into Users (user_name, email, password, lastLogin, status, createdAt, updatedAt) values ('Ronald Reagan', 'email12@email.com', 'password1234', current_timestamp(), 'inactive', current_timestamp(), current_timestamp());
insert into Users (user_name, email, password, lastLogin, status, createdAt, updatedAt) values ('Wayne Johnson', 'email13@email.com', 'password1234', current_timestamp(), 'inactive', current_timestamp(), current_timestamp());
insert into Users (user_name, email, password, lastLogin, status, createdAt, updatedAt) values ('TA Tom', 'email14@email.com', 'password1234', current_timestamp(), 'inactive', current_timestamp(), current_timestamp());
insert into Users (user_name, email, password, lastLogin, status, createdAt, updatedAt) values ('Stan Smith', 'email15@email.com', 'password1234', current_timestamp(), 'inactive', current_timestamp(), current_timestamp());
insert into Users (user_name, email, password, lastLogin, status, createdAt, updatedAt) values ('Rodger Smith', 'email16@email.com', 'password1234', current_timestamp(), 'inactive', current_timestamp(), current_timestamp());
insert into Users (user_name, email, password, lastLogin, status, createdAt, updatedAt) values ('Steve Smith', 'email17@email.com', 'password1234', current_timestamp(), 'inactive', current_timestamp(), current_timestamp());
insert into Users (user_name, email, password, lastLogin, status, createdAt, updatedAt) values ('Jimmie Hendrix', 'email18@email.com', 'password1234', current_timestamp(), 'inactive', current_timestamp(), current_timestamp());
insert into Users (user_name, email, password, lastLogin, status, createdAt, updatedAt) values ('Luke Nix', 'email19@email.com', 'password1234', current_timestamp(), 'inactive', current_timestamp(), current_timestamp());
insert into Users (user_name, email, password, lastLogin, status, createdAt, updatedAt) values ('Frank the Tank', 'email20@email.com', 'password1234', current_timestamp(), 'inactive', current_timestamp(), current_timestamp());
insert into Users (user_name, email, password, lastLogin, status, createdAt, updatedAt) values ('Surfer Dude', 'email21@email.com', 'password1234', current_timestamp(), 'inactive', current_timestamp(), current_timestamp());

insert into Posts (region, city, post_title, post_body, post_points, createdAt, updatedAt, UserId) values ('South West','Houston','Great Surf','The Waves are so crunchy! I never want to leave this spot!', 0,current_timestamp(), current_timestamp(), 2);
insert into Posts (region, city, post_title, post_body, post_points, createdAt, updatedAt, UserId) values ('East Coast','Miami','No Surf','I came here to ride some waves. None here, Maybe I try skim boarding, lol!', 0,current_timestamp(), current_timestamp(), 6);
insert into Posts (region, city, post_title, post_body, post_points, createdAt, updatedAt, UserId) values ('West Coast','San Diego','Crazy Rip Tide','Be safe out there. The wave are wicked and so is the rip tide, keep an eye on your fellow kooks', 0,current_timestamp(), current_timestamp(), 14);
insert into Posts (region, city, post_title, post_body, post_points, createdAt, updatedAt, UserId) values ('Gulf Coast','Naples','Bad Smell','Bad Smell at the beach. Its to nasty to be here', 0,current_timestamp(), current_timestamp(), 11);
insert into Posts (region, city, post_title, post_body, post_points, createdAt, updatedAt, UserId) values ('West Coast','San Fransisco','Gnarly Winds','The wind is kick up some sand, not a good place to lay out and get a sun burn right now', 0,current_timestamp(), current_timestamp(), 19);
insert into Posts (region, city, post_title, post_body, post_points, createdAt, updatedAt, UserId) values ('Hawaii','Honalulu','Awesomeness','The water is perfect, Time to get wet!', 0,current_timestamp(), current_timestamp(), 15);

select * from Posts;